name: Build

on:
  push:
    branches:
      - 'master' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Convert style.yml to style.json
        run: |
          npm install
          npm run build
          ./create-sprite.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: 'gh-pages'
          folder: './docs/'
          target-folder: './'